### ISSUE TITLE
Readme references `target-mssql` instead of `tap-mssql`

### ISSUE THREAD

**Issue by visch** [BuzzCutNorman/tap-mssql#63]
Couple spots in the Readme, hit errors when copy pasting from the readme

**Comment by BuzzCutNorman** [comment]
@visch Thanks for bring this to my attention.  I think I got the instances you mentioned.  If you have time please reviews this updated readme and let me know if you see anything I missed.
https://github.com/BuzzCutNorman/tap-mssql/tree/63-correct-wrong-config-commands
