### ISSUE TITLE
Pendulum dependency missing

### ISSUE THREAD

**Issue by anna-nylander** [BuzzCutNorman/tap-mssql#79]
I'm using this tap in a meltano project and since the latest release the tap crashes due to missing import. The "Pendulum" python package is removed in [meltano SDK 0.39.1](https://github.com/meltano/sdk/releases/tag/v0.39.1), but still used by this tap and not installed explicitly. Maybe we can add pendulum to the poetry dependencies or use another package for datetimes? Thanks :)

**Comment by BuzzCutNorman** [comment]
Thank you for pointing this out and the PR to resolve the issue.  If you would please give this PR a try and see if it resolves your issue.

https://github.com/BuzzCutNorman/tap-mssql.git@encoding-via-msgspec

**Comment by BuzzCutNorman** [comment]
Thank You! Anna
